### ISSUE TITLE
Per User

### ISSUE THREAD

**Issue by difi80211g** [sugarcrm/IPRestrictionManager#1]
Is it possible to make the IP restriction work on a per user basis instead of all users?  For example all of our users are synced with LDAP and have password policies and lock outs.  Two of our users are local users and we do not want a brute force against them.  Can i lock out just these two from logging into sugarcrm from anything but a 10.x.x.x address and allow everyone else to still login remote?

**Comment by geraldclark** [comment]
Hi @difi80211g,

The module only works on a per user basis. If a user doesn't have any restrictions applied, they will be able to log in from any ip address. Hope this helps!
